import os

VariantDir('build', 'src', duplicate=False)
env = Environment(
	CPPPATH=['./include'],
	CXXFLAGS='-g -Wall -std=c++17'
)
env['ENV']['TERM'] = os.environ['TERM'] # Colored output

env.Program( "bin/viewer", [ Glob("build/*.cc") ] )
